version: 2

sources:
  - name: jaffle_shop
    database: raw
    tables:
      - name: orders
        description: Raw order data
        loaded_at_field: _etl_loaded_at
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
        columns:
          - name: id
            tests:
              - unique

      - name: customers
        description: Raw customer data
        columns:
          - name: id
            tests:
              - unique        

  - name: stripe
    description: Raw loaded by Stripe
    database: raw
    tables:
      - name: payment
        description: Raw payment data loaded by Stripe